// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetD__N7q5iQjEkx7zWBrNQ8ZE5Rom8R8',
    appId: '1:898531426441:web:4e8c106a1d79b336ad4658',
    messagingSenderId: '898531426441',
    projectId: 'chat109-76689',
    authDomain: 'chat109-76689.firebaseapp.com',
    storageBucket: 'chat109-76689.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5UFRzst0DEDIwRtbXon1bszZ9bP4KUw',
    appId: '1:898531426441:android:c8c4426f11491aefad4658',
    messagingSenderId: '898531426441',
    projectId: 'chat109-76689',
    storageBucket: 'chat109-76689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpIaf--CHvfaN8gO12OUiPlLp1BwIdcA',
    appId: '1:898531426441:ios:c16b86a53dae6557ad4658',
    messagingSenderId: '898531426441',
    projectId: 'chat109-76689',
    storageBucket: 'chat109-76689.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqpIaf--CHvfaN8gO12OUiPlLp1BwIdcA',
    appId: '1:898531426441:ios:c16b86a53dae6557ad4658',
    messagingSenderId: '898531426441',
    projectId: 'chat109-76689',
    storageBucket: 'chat109-76689.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetD__N7q5iQjEkx7zWBrNQ8ZE5Rom8R8',
    appId: '1:898531426441:web:5f7f44057e414498ad4658',
    messagingSenderId: '898531426441',
    projectId: 'chat109-76689',
    authDomain: 'chat109-76689.firebaseapp.com',
    storageBucket: 'chat109-76689.firebasestorage.app',
  );
}
